version: 2.1

orbs:
  maven: circleci/maven@1.4.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.2-jdk-stretch
    steps:
      - checkout
      - run: mvn clean package
      - run:
          name: Creating Dummy Artifacts
          command: |
            mkdir artifacts;
            echo "my artifact file" > artifacts/art-1;
      - store_artifacts:
          path: artifacts/
          destination: artifact.jar

  test:
    docker:
      - image: circleci/openjdk:11.0.2-jdk-stretch
    steps:
      - checkout
      - run: mvn test

workflows:
  maven_test:
    jobs:
      - test
      - build
