version: 2.1

orbs:
  maven: circleci/maven@1.4.1

jobs:
  build:
    # working_directory: /tmp
    docker:
      - image: circleci/openjdk:11.0.2-jdk-stretch
    steps:
      - checkout
      - run: mvn clean package
      - run:
          name: Creating Dummy Artifacts
          command: |
            mkdir artifacts;
            echo "my artifact file" > artifacts/art-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > artifacts/art-2;
      - store_artifacts:
          path: artifacts/art-1
          destination: artifact-file
      - store_artifacts:
          path: artifacts

  test:
    docker:
      - image: circleci/openjdk:11.0.2-jdk-stretch
    steps:
      - checkout
      - run: mvn test

workflows:
  maven_test:
    jobs:
      - test
      - build
