version: 2.1

orbs:
  maven: circleci/maven@1.4.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.2-jdk-stretch
    steps:
      - checkout
      - run: mvn clean package
      
    working_directory: /tmp
    steps:
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/art-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/art-2;
      - store_artifacts:
          path: /tmp/art-1
          destination: artifact-file
      - store_artifacts:
          path: /tmp/artifacts

  test:
    docker:
      - image: circleci/openjdk:11.0.2-jdk-stretch
    steps:
      - checkout
      - run: mvn test
          
workflows:
  maven_test:
    jobs:
      - test
      - build
