version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.2-jdk-stretch
    steps:
      - checkout
      - maven/install
      - run: mvn clean package

  test:
    docker:
      - image: circleci/openjdk:11.0.2-jdk-stretch
    steps:
      - checkout
      - maven/install
      - run: mvn test

workflows:
  build_and_test:
    jobs:
      - build
      - test
