version: 2.1

orbs:
  maven: circleci/maven@1.4.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.2-jdk-stretch
    steps:
      - checkout
      - run: mvn clean package

  test:
    docker:
      - image: circleci/openjdk:11.0.2-jdk-stretch
    steps:
      - checkout
      - run: mvn test

workflows:
  maven_test:
    jobs:
      - build
      - test
