version: 2.1

orbs:
  maven: circleci/maven@1.4.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.2-jdk-stretch
    steps:
      - checkout
      - run: mvn clean package
      - store_artifacts:
          path: /home/circleci/project/target/
          destination: SimpleWebApp-1.0-SNAPSHOT.war

  test:
    docker:
      - image: circleci/openjdk:11.0.2-jdk-stretch
    steps:
      - checkout
      - run: mvn test

workflows:
  maven_test:
    jobs:
      - test
      - build
