version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  build:
    steps:
      - run: 
          name: Build 
          command: mvn clean package
        
workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
